// Map workout template category codes to Banco de Exercícios grupo/subcategoria
export const CODE_TO_GRUPO: Record<string, string> = {
  LIB: "Liberação Miofascial",
  MOB: "Mobilidade Articular",
  ATI: "Ativação Muscular",
  PREV: "Preventivo",
  COND: "Cardio",
  DJS: "Força",
  DJA: "Força",
  DQ: "Força",
  DQ_P: "Força",
  PH: "Força",
  PV: "Força",
  EH: "Força",
  EV: "Força",
  EP: "Força",
  EEF: "Força",
  EE: "Força",
  AH: "Força",
  AF: "Força",
  AR: "Força",
  KB: "Força",
  PLIO: "Força",
  ISO: "Força",
  ABD: "Força",
  ET: "Força",
  LPO: "Força",
  AUX: "Força",
};

export const CODE_TO_SUBCATEGORIA: Record<string, string | undefined> = {
  DJS: "Dominante de Joelho Simétrico",
  DJA: "Dominante de Joelhos Assimétrico",
  DQ: "Dominante de Quadril",
  DQ_P: "Dominante de Quadril Posterior",
  PH: "Puxar Horizontal",
  PV: "Puxar Vertical",
  EH: "Empurrar Horizontal",
  EV: "Empurrar Vertical",
  EP: "Estabilidade Posterior",
  EEF: "Estabilidade Escapular",
  EE: "Estabilidade Escapular",
  AH: "Anti-Hiperextensão",
  AF: "Anti-flexão",
  AR: "Anti-Rotação",
  KB: "Kettlebell",
  PLIO: "Pliometria",
  ISO: "Isoinercial",
  ABD: "Abdominais",
  ET: "Extensão Torácica",
  LPO: "LPO",
  AUX: "Auxiliares",
};

// GRUPO_SUBCATEGORIAS e AQUECIMENTO_SUBCATEGORIAS foram removidos.
// A taxonomia agora vem do banco via useExerciseCategories().
