project_id = "dmudgqedzeosfpehpgep"

[functions.agenda-ics]
verify_jwt = false

[functions.rede-salvar-cartao]
verify_jwt = false

[functions.corrida-lookup-cpf]
verify_jwt = false

[functions.corrida-registrar-inscricao]
verify_jwt = false

[functions.corrida-criar-pedido]
verify_jwt = true

[functions.corrida-status-tokenizacao]
verify_jwt = false

[functions.corrida-aceitar-contrato]
verify_jwt = false

[functions.corrida-cobrar-pedido]
verify_jwt = false


[functions.corrida-atualizar-inscricao-prova]
verify_jwt = false

[functions.corrida-enviar-confirmacao-email]
verify_jwt = false
