// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-alunos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_alunos_default = defineTool({
  name: "list_alunos",
  title: "Listar alunos",
  description: "Lista alunos da Fortem vis\xEDveis para o usu\xE1rio autenticado. Suporta busca por nome/e-mail/CPF e filtro por status.",
  inputSchema: {
    busca: z.string().optional().describe("Trecho de nome, e-mail ou CPF."),
    status: z.enum(["ativo", "inativo"]).optional().describe("Filtra pelo status do aluno."),
    limite: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de linhas (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, status, limite }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("alunos").select("id, nome, email, telefone, cpf, status, frequencia_semanal, cidade, uf").order("nome", { ascending: true }).limit(limite ?? 25);
    if (status) q = q.eq("status", status);
    if (busca?.trim()) {
      const term = `%${busca.trim()}%`;
      q = q.or(`nome.ilike.${term},email.ilike.${term},cpf.ilike.${term}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { alunos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-aluno.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_aluno_default = defineTool2({
  name: "get_aluno",
  title: "Detalhes do aluno",
  description: "Retorna os dados de um aluno pelo id (uuid).",
  inputSchema: {
    aluno_id: z2.string().uuid().describe("UUID do aluno.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ aluno_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("alunos").select("*").eq("id", aluno_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Aluno n\xE3o encontrado" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { aluno: data }
    };
  }
});

// src/lib/mcp/tools/agenda-do-dia.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var agenda_do_dia_default = defineTool3({
  name: "agenda_do_dia",
  title: "Agenda do dia",
  description: "Lista os agendamentos (agenda_servicos) de uma data espec\xEDfica (padr\xE3o: hoje). Inclui recorrentes do dia da semana e pontuais na data.",
  inputSchema: {
    data: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data no formato YYYY-MM-DD. Se omitido, usa a data atual.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ data: dataArg }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const target = dataArg ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const diaSemana = (/* @__PURE__ */ new Date(target + "T12:00:00")).getDay();
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("agenda_servicos").select("id, atividade, local, horario_inicio, horario_fim, tipo, dia_semana, data_especifica, aluno_id, profissional_id").or(
      `and(tipo.eq.recorrente,dia_semana.eq.${diaSemana}),and(tipo.eq.pontual,data_especifica.eq.${target})`
    ).order("horario_inicio", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: `Agenda de ${target} (${data?.length ?? 0} itens):
${JSON.stringify(data ?? [], null, 2)}`
        }
      ],
      structuredContent: { data: target, itens: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dmudgqedzeosfpehpgep";
var mcp_default = defineMcp({
  name: "fortem-mcp",
  title: "Fortem Gest\xE3o T\xE9cnica",
  version: "0.1.0",
  instructions: "Ferramentas de leitura da Fortem Gest\xE3o T\xE9cnica. Use `list_alunos` para buscar alunos, `get_aluno` para detalhes de um aluno espec\xEDfico e `agenda_do_dia` para ver os agendamentos de uma data. Todas as ferramentas respeitam as permiss\xF5es (RLS) do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_alunos_default, get_aluno_default, agenda_do_dia_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
